spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/postgres
    username: postgres
    password: password
    hikari:
      schema: public
      idle-timeout: ${DB_IDLE_TIMEOUT:10000}
      minimum-idle: ${DB_MINIMUM_IDLE:0}
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE:4}
      data-source-properties:
        ApplicationName: ${spring.application.name}
  application:
    name: test

server:
  port: 8081